export const TABLE_ADMINISTRATOR = 'ADMINISTRATOR';
export const TABLE_INFORMATION = 'INFORMATION';
export const TABLE_TRANSACTIONS = 'TRANSACTIONS';
export const TABLE_EXCLUDED_DATES = 'EXCLUDED_DATES';