import { createAction } from 'redux-actions';

export const ATTRACTION_ONMOUNT_REQUEST_NAME = 'ATTRACTION_ONMOUNT_REQUEST';
export const ATTRACTION_ONMOUNT_REQUEST = createAction(ATTRACTION_ONMOUNT_REQUEST_NAME);

export const ATTRACTION_ONMOUNT_SUCCESS_NAME = 'ATTRACTION_ONMOUNT_SUCCESS';
export const ATTRACTION_ONMOUNT_SUCCESS = createAction(ATTRACTION_ONMOUNT_SUCCESS_NAME);

export const ATTRACTION_ONMOUNT_ERROR_NAME = 'ATTRACTION_ONMOUNT_ERROR';
export const ATTRACTION_ONMOUNT_ERROR = createAction(ATTRACTION_ONMOUNT_ERROR_NAME);