import { createAction } from 'redux-actions';

export const BULLETIN_ONMOUNT_REQUEST_NAME = 'BULLETIN_ONMOUNT_REQUEST';
export const BULLETIN_ONMOUNT_REQUEST = createAction(BULLETIN_ONMOUNT_REQUEST_NAME);

export const BULLETIN_ONMOUNT_SUCCESS_NAME = 'BULLETIN_ONMOUNT_SUCCESS';
export const BULLETIN_ONMOUNT_SUCCESS = createAction(BULLETIN_ONMOUNT_SUCCESS_NAME);

export const BULLETIN_ONMOUNT_ERROR_NAME = 'BULLETIN_ONMOUNT_ERROR';
export const BULLETIN_ONMOUNT_ERROR = createAction(BULLETIN_ONMOUNT_ERROR_NAME);