import { createAction } from 'redux-actions';

export const CONTACT_ONMOUNT_REQUEST_NAME = 'CONTACT_ONMOUNT_REQUEST';
export const CONTACT_ONMOUNT_REQUEST = createAction(CONTACT_ONMOUNT_REQUEST_NAME);

export const CONTACT_ONMOUNT_SUCCESS_NAME = 'CONTACT_ONMOUNT_SUCCESS';
export const CONTACT_ONMOUNT_SUCCESS = createAction(CONTACT_ONMOUNT_SUCCESS_NAME);

export const CONTACT_ONMOUNT_ERROR_NAME = 'CONTACT_ONMOUNT_ERROR';
export const CONTACT_ONMOUNT_ERROR = createAction(CONTACT_ONMOUNT_ERROR_NAME);