import { createAction } from 'redux-actions';

export const DASHBOARD_SETTINGS_ONMOUNT_REQUEST_NAME = 'DASHBOARD_SETTINGS_ONMOUNT_REQUEST';
export const DASHBOARD_SETTINGS_ONMOUNT_REQUEST = createAction(DASHBOARD_SETTINGS_ONMOUNT_REQUEST_NAME);
export const DASHBOARD_SETTINGS_ONMOUNT_SUCCESS_NAME = 'DASHBOARD_SETTINGS_ONMOUNT_SUCCESS';
export const DASHBOARD_SETTINGS_ONMOUNT_SUCCESS = createAction(DASHBOARD_SETTINGS_ONMOUNT_SUCCESS_NAME);
export const DASHBOARD_SETTINGS_ONMOUNT_ERROR_NAME = 'DASHBOARD_SETTINGS_ONMOUNT_ERROR';
export const DASHBOARD_SETTINGS_ONMOUNT_ERROR = createAction(DASHBOARD_SETTINGS_ONMOUNT_ERROR_NAME);

export const DASHBOARD_SETTINGS_DELETE_NAME = 'DASHBOARD_SETTINGS_DELETE';
export const DASHBOARD_SETTINGS_DELETE = createAction(DASHBOARD_SETTINGS_DELETE_NAME);

export const DASHBOARD_SETTINGS_SUBMIT_REQUEST_NAME = 'DASHBOARD_SETTINGS_SUBMIT_REQUEST';
export const DASHBOARD_SETTINGS_SUBMIT_REQUEST = createAction(DASHBOARD_SETTINGS_SUBMIT_REQUEST_NAME);
export const DASHBOARD_SETTINGS_SUBMIT_SUCCESS_NAME = 'DASHBOARD_SETTINGS_SUBMIT_SUCCESS';
export const DASHBOARD_SETTINGS_SUBMIT_SUCCESS = createAction(DASHBOARD_SETTINGS_SUBMIT_SUCCESS_NAME);
export const DASHBOARD_SETTINGS_SUBMIT_ERROR_NAME = 'DASHBOARD_SETTINGS_SUBMIT_ERROR';
export const DASHBOARD_SETTINGS_SUBMIT_ERROR = createAction(DASHBOARD_SETTINGS_SUBMIT_ERROR_NAME);
