import { createAction } from 'redux-actions';

export const DASHBOARD_HOME_ONMOUNT_REQUEST_NAME = 'DASHBOARD_HOME_ONMOUNT_REQUEST';
export const DASHBOARD_HOME_ONMOUNT_REQUEST = createAction(DASHBOARD_HOME_ONMOUNT_REQUEST_NAME);
export const DASHBOARD_HOME_ONMOUNT_SUCCESS_NAME = 'DASHBOARD_HOME_ONMOUNT_SUCCESS';
export const DASHBOARD_HOME_ONMOUNT_SUCCESS = createAction(DASHBOARD_HOME_ONMOUNT_SUCCESS_NAME);
export const DASHBOARD_HOME_ONMOUNT_ERROR_NAME = 'DASHBOARD_HOME_ONMOUNT_ERROR';
export const DASHBOARD_HOME_ONMOUNT_ERROR = createAction(DASHBOARD_HOME_ONMOUNT_ERROR_NAME);

export const DASHBOARD_HOME_DELETE_NAME = 'DASHBOARD_HOME_DELETE';
export const DASHBOARD_HOME_DELETE = createAction(DASHBOARD_HOME_DELETE_NAME);
export const DASHBOARD_HOME_NEW_NAME = 'DASHBOARD_HOME_NEW';
export const DASHBOARD_HOME_NEW = createAction(DASHBOARD_HOME_NEW_NAME);
export const DASHBOARD_HOME_RESET_NAME = 'DASHBOARD_HOME_RESET';
export const DASHBOARD_HOME_RESET = createAction(DASHBOARD_HOME_RESET_NAME);

export const DASHBOARD_HOME_WATCH_NAME = 'DASHBOARD_HOME_WATCH';
export const DASHBOARD_HOME_WATCH = createAction(DASHBOARD_HOME_WATCH_NAME);

export const DASHBOARD_HOME_SUBMIT_REQUEST_NAME = 'DASHBOARD_HOME_SUBMIT_REQUEST';
export const DASHBOARD_HOME_SUBMIT_REQUEST = createAction(DASHBOARD_HOME_SUBMIT_REQUEST_NAME);
export const DASHBOARD_HOME_SUBMIT_SUCCESS_NAME = 'DASHBOARD_HOME_SUBMIT_SUCCESS';
export const DASHBOARD_HOME_SUBMIT_SUCCESS = createAction(DASHBOARD_HOME_SUBMIT_SUCCESS_NAME);
export const DASHBOARD_HOME_SUBMIT_ERROR_NAME = 'DASHBOARD_HOME_SUBMIT_ERROR';
export const DASHBOARD_HOME_SUBMIT_ERROR = createAction(DASHBOARD_HOME_SUBMIT_ERROR_NAME);
