import { createAction } from 'redux-actions';

export const DASHBOARD_STORIES_ONMOUNT_REQUEST_NAME = 'DASHBOARD_STORIES_ONMOUNT_REQUEST';
export const DASHBOARD_STORIES_ONMOUNT_REQUEST = createAction(DASHBOARD_STORIES_ONMOUNT_REQUEST_NAME);
export const DASHBOARD_STORIES_ONMOUNT_SUCCESS_NAME = 'DASHBOARD_STORIES_ONMOUNT_SUCCESS';
export const DASHBOARD_STORIES_ONMOUNT_SUCCESS = createAction(DASHBOARD_STORIES_ONMOUNT_SUCCESS_NAME);
export const DASHBOARD_STORIES_ONMOUNT_ERROR_NAME = 'DASHBOARD_STORIES_ONMOUNT_ERROR';
export const DASHBOARD_STORIES_ONMOUNT_ERROR = createAction(DASHBOARD_STORIES_ONMOUNT_ERROR_NAME);

export const DASHBOARD_STORIES_DELETE_NAME = 'DASHBOARD_STORIES_DELETE';
export const DASHBOARD_STORIES_DELETE = createAction(DASHBOARD_STORIES_DELETE_NAME);
export const DASHBOARD_STORIES_NEW_NAME = 'DASHBOARD_STORIES_NEW';
export const DASHBOARD_STORIES_NEW = createAction(DASHBOARD_STORIES_NEW_NAME);
export const DASHBOARD_STORIES_RESET_NAME = 'DASHBOARD_STORIES_RESET';
export const DASHBOARD_STORIES_RESET = createAction(DASHBOARD_STORIES_RESET_NAME);

export const DASHBOARD_STORIES_WATCH_NAME = 'DASHBOARD_STORIES_WATCH';
export const DASHBOARD_STORIES_WATCH = createAction(DASHBOARD_STORIES_WATCH_NAME);

export const DASHBOARD_STORIES_SUBMIT_REQUEST_NAME = 'DASHBOARD_STORIES_SUBMIT_REQUEST';
export const DASHBOARD_STORIES_SUBMIT_REQUEST = createAction(DASHBOARD_STORIES_SUBMIT_REQUEST_NAME);
export const DASHBOARD_STORIES_SUBMIT_SUCCESS_NAME = 'DASHBOARD_STORIES_SUBMIT_SUCCESS';
export const DASHBOARD_STORIES_SUBMIT_SUCCESS = createAction(DASHBOARD_STORIES_SUBMIT_SUCCESS_NAME);
export const DASHBOARD_STORIES_SUBMIT_ERROR_NAME = 'DASHBOARD_STORIES_SUBMIT_ERROR';
export const DASHBOARD_STORIES_SUBMIT_ERROR = createAction(DASHBOARD_STORIES_SUBMIT_ERROR_NAME);
