import { createAction } from 'redux-actions';

export const DASHBOARD_BULLETIN_ONMOUNT_REQUEST_NAME = 'DASHBOARD_BULLETIN_ONMOUNT_REQUEST';
export const DASHBOARD_BULLETIN_ONMOUNT_REQUEST = createAction(DASHBOARD_BULLETIN_ONMOUNT_REQUEST_NAME);
export const DASHBOARD_BULLETIN_ONMOUNT_SUCCESS_NAME = 'DASHBOARD_BULLETIN_ONMOUNT_SUCCESS';
export const DASHBOARD_BULLETIN_ONMOUNT_SUCCESS = createAction(DASHBOARD_BULLETIN_ONMOUNT_SUCCESS_NAME);
export const DASHBOARD_BULLETIN_ONMOUNT_ERROR_NAME = 'DASHBOARD_BULLETIN_ONMOUNT_ERROR';
export const DASHBOARD_BULLETIN_ONMOUNT_ERROR = createAction(DASHBOARD_BULLETIN_ONMOUNT_ERROR_NAME);

export const DASHBOARD_BULLETIN_DELETE_NAME = 'DASHBOARD_BULLETIN_DELETE';
export const DASHBOARD_BULLETIN_DELETE = createAction(DASHBOARD_BULLETIN_DELETE_NAME);
export const DASHBOARD_BULLETIN_NEW_NAME = 'DASHBOARD_BULLETIN_NEW';
export const DASHBOARD_BULLETIN_NEW = createAction(DASHBOARD_BULLETIN_NEW_NAME);
export const DASHBOARD_BULLETIN_RESET_NAME = 'DASHBOARD_BULLETIN_RESET';
export const DASHBOARD_BULLETIN_RESET = createAction(DASHBOARD_BULLETIN_RESET_NAME);

export const DASHBOARD_BULLETIN_WATCH_NAME = 'DASHBOARD_BULLETIN_WATCH';
export const DASHBOARD_BULLETIN_WATCH = createAction(DASHBOARD_BULLETIN_WATCH_NAME);

export const DASHBOARD_BULLETIN_SUBMIT_REQUEST_NAME = 'DASHBOARD_BULLETIN_SUBMIT_REQUEST';
export const DASHBOARD_BULLETIN_SUBMIT_REQUEST = createAction(DASHBOARD_BULLETIN_SUBMIT_REQUEST_NAME);
export const DASHBOARD_BULLETIN_SUBMIT_SUCCESS_NAME = 'DASHBOARD_BULLETIN_SUBMIT_SUCCESS';
export const DASHBOARD_BULLETIN_SUBMIT_SUCCESS = createAction(DASHBOARD_BULLETIN_SUBMIT_SUCCESS_NAME);
export const DASHBOARD_BULLETIN_SUBMIT_ERROR_NAME = 'DASHBOARD_BULLETIN_SUBMIT_ERROR';
export const DASHBOARD_BULLETIN_SUBMIT_ERROR = createAction(DASHBOARD_BULLETIN_SUBMIT_ERROR_NAME);
