import { createAction } from 'redux-actions';

export const DASHBOARD_CONTACT_ONMOUNT_REQUEST_NAME = 'DASHBOARD_CONTACT_ONMOUNT_REQUEST';
export const DASHBOARD_CONTACT_ONMOUNT_REQUEST = createAction(DASHBOARD_CONTACT_ONMOUNT_REQUEST_NAME);
export const DASHBOARD_CONTACT_ONMOUNT_SUCCESS_NAME = 'DASHBOARD_CONTACT_ONMOUNT_SUCCESS';
export const DASHBOARD_CONTACT_ONMOUNT_SUCCESS = createAction(DASHBOARD_CONTACT_ONMOUNT_SUCCESS_NAME);
export const DASHBOARD_CONTACT_ONMOUNT_ERROR_NAME = 'DASHBOARD_CONTACT_ONMOUNT_ERROR';
export const DASHBOARD_CONTACT_ONMOUNT_ERROR = createAction(DASHBOARD_CONTACT_ONMOUNT_ERROR_NAME);

export const DASHBOARD_CONTACT_RESET_NAME = 'DASHBOARD_CONTACT_RESET';
export const DASHBOARD_CONTACT_RESET = createAction(DASHBOARD_CONTACT_RESET_NAME);

export const DASHBOARD_CONTACT_WATCH_NAME = 'DASHBOARD_CONTACT_WATCH';
export const DASHBOARD_CONTACT_WATCH = createAction(DASHBOARD_CONTACT_WATCH_NAME);

export const DASHBOARD_CONTACT_SUBMIT_REQUEST_NAME = 'DASHBOARD_CONTACT_SUBMIT_REQUEST';
export const DASHBOARD_CONTACT_SUBMIT_REQUEST = createAction(DASHBOARD_CONTACT_SUBMIT_REQUEST_NAME);
export const DASHBOARD_CONTACT_SUBMIT_SUCCESS_NAME = 'DASHBOARD_CONTACT_SUBMIT_SUCCESS';
export const DASHBOARD_CONTACT_SUBMIT_SUCCESS = createAction(DASHBOARD_CONTACT_SUBMIT_SUCCESS_NAME);
export const DASHBOARD_CONTACT_SUBMIT_ERROR_NAME = 'DASHBOARD_CONTACT_SUBMIT_ERROR';
export const DASHBOARD_CONTACT_SUBMIT_ERROR = createAction(DASHBOARD_CONTACT_SUBMIT_ERROR_NAME);
