import { createAction } from 'redux-actions';

export const DASHBOARD_RESOURCES_ONMOUNT_REQUEST_NAME = 'DASHBOARD_RESOURCES_ONMOUNT_REQUEST';
export const DASHBOARD_RESOURCES_ONMOUNT_REQUEST = createAction(DASHBOARD_RESOURCES_ONMOUNT_REQUEST_NAME);
export const DASHBOARD_RESOURCES_ONMOUNT_SUCCESS_NAME = 'DASHBOARD_RESOURCES_ONMOUNT_SUCCESS';
export const DASHBOARD_RESOURCES_ONMOUNT_SUCCESS = createAction(DASHBOARD_RESOURCES_ONMOUNT_SUCCESS_NAME);
export const DASHBOARD_RESOURCES_ONMOUNT_ERROR_NAME = 'DASHBOARD_RESOURCES_ONMOUNT_ERROR';
export const DASHBOARD_RESOURCES_ONMOUNT_ERROR = createAction(DASHBOARD_RESOURCES_ONMOUNT_ERROR_NAME);

export const DASHBOARD_RESOURCES_DELETE_NAME = 'DASHBOARD_RESOURCES_DELETE';
export const DASHBOARD_RESOURCES_DELETE = createAction(DASHBOARD_RESOURCES_DELETE_NAME);
export const DASHBOARD_RESOURCES_NEW_NAME = 'DASHBOARD_RESOURCES_NEW';
export const DASHBOARD_RESOURCES_NEW = createAction(DASHBOARD_RESOURCES_NEW_NAME);
export const DASHBOARD_RESOURCES_RESET_NAME = 'DASHBOARD_RESOURCES_RESET';
export const DASHBOARD_RESOURCES_RESET = createAction(DASHBOARD_RESOURCES_RESET_NAME);

export const DASHBOARD_RESOURCES_WATCH_NAME = 'DASHBOARD_RESOURCES_WATCH';
export const DASHBOARD_RESOURCES_WATCH = createAction(DASHBOARD_RESOURCES_WATCH_NAME);

export const DASHBOARD_RESOURCES_SUBMIT_REQUEST_NAME = 'DASHBOARD_RESOURCES_SUBMIT_REQUEST';
export const DASHBOARD_RESOURCES_SUBMIT_REQUEST = createAction(DASHBOARD_RESOURCES_SUBMIT_REQUEST_NAME);
export const DASHBOARD_RESOURCES_SUBMIT_SUCCESS_NAME = 'DASHBOARD_RESOURCES_SUBMIT_SUCCESS';
export const DASHBOARD_RESOURCES_SUBMIT_SUCCESS = createAction(DASHBOARD_RESOURCES_SUBMIT_SUCCESS_NAME);
export const DASHBOARD_RESOURCES_SUBMIT_ERROR_NAME = 'DASHBOARD_RESOURCES_SUBMIT_ERROR';
export const DASHBOARD_RESOURCES_SUBMIT_ERROR = createAction(DASHBOARD_RESOURCES_SUBMIT_ERROR_NAME);
