import { createAction } from 'redux-actions';

export const EXPLORE_ONMOUNT_REQUEST_NAME = 'EXPLORE_ONMOUNT_REQUEST';
export const EXPLORE_ONMOUNT_REQUEST = createAction(EXPLORE_ONMOUNT_REQUEST_NAME);

export const EXPLORE_ONMOUNT_SUCCESS_NAME = 'EXPLORE_ONMOUNT_SUCCESS';
export const EXPLORE_ONMOUNT_SUCCESS = createAction(EXPLORE_ONMOUNT_SUCCESS_NAME);

export const EXPLORE_ONMOUNT_ERROR_NAME = 'EXPLORE_ONMOUNT_ERROR';
export const EXPLORE_ONMOUNT_ERROR = createAction(EXPLORE_ONMOUNT_ERROR_NAME);