import { createAction } from 'redux-actions';

export const RESOURCES_ONMOUNT_REQUEST_NAME = 'RESOURCES_ONMOUNT_REQUEST';
export const RESOURCES_ONMOUNT_REQUEST = createAction(RESOURCES_ONMOUNT_REQUEST_NAME);

export const RESOURCES_ONMOUNT_SUCCESS_NAME = 'RESOURCES_ONMOUNT_SUCCESS';
export const RESOURCES_ONMOUNT_SUCCESS = createAction(RESOURCES_ONMOUNT_SUCCESS_NAME);

export const RESOURCES_ONMOUNT_ERROR_NAME = 'RESOURCES_ONMOUNT_ERROR';
export const RESOURCES_ONMOUNT_ERROR = createAction(RESOURCES_ONMOUNT_ERROR_NAME);